### ISSUE TITLE
Remove explicit system path manipulation

### ISSUE THREAD

**Issue by mschmidt87** [jakobj/python-gp#26]
Once #19 has been merged, we can remove the lines that add the location of the package to the system path explicitly from all example and test scripts.

**Comment by jakobj** [comment]
afterwards E402 should be enabled again for flake8

**Comment by mschmidt87** [comment]
and we should edit the travis file. It will no longer be necessary to `cd` into the test folder.

**Comment by mschmidt87** [comment]
One question: I think there are two possible approaches:
1. Keep the test suite at the top-level of the repo and then just do  `import gp` everywhere. That implies that the library needs to be installed before testing.
2. Move `test/` into `gp/` and then do `from .. import gp` everywhere. This is what is done in `python-dicthash` for instance. We can still exclude the test suite from being installed in the `setup.py`.
What do you think, @jakobj ?

**Comment by jakobj** [comment]
i would strongly be in favor of 1. since one can just install in dev mode so that one does not have to reinstall after every change (`pip install -e`, see, e.g., https://stackoverflow.com/questions/35064426/when-would-the-e-editable-option-be-useful-with-pip-install), and keeping the tests separately seems like common practice
